### ISSUE TITLE
trying to skip instruction, but seems unimplemented

### ISSUE THREAD

**Issue by liordror** [quarkslab/tritondse#15] opened 2023-09-21 16:28 UTC
hi:)
I try to use the command  se.skip_instruction() in a callback that is registered using the function register_pre_imported_routine_callback in order to relpace the original function with my function (like you suggested in issue from June 6). when the callback runs, it raises the error SkipInstructionException("Skip instruction"). I looked at the code, and the only line in the function skip_instruction() is raising the exception. Should i implement this function, or did i use it wrong?

**Comment by cnheitman** [comment] 2024-01-03 18:12
Hi! Indeed, `skip_instruction` raises an exception that is caught by the `step` function which returns intermediately after doing it. This way the instruction is skipped as intended. 

There seems a fix to this mechanism was applied on commit cc3726e4efb76d02265eac6d7ed04c1203200939.

I'm closing this issue. If you still have the issue, please re-open it.

**Closed by cnheitman** 2024-01-03 18:12 UTC
